name: tiktorch-server-env
channels:
  - ilastik-forge
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - lapack
  - mypy
  - pickle5
  - python=3.7.*
  - scipy=1.2.*  # 1.3 removed imsave
  - paramiko=2.4.2
  - inferno=v0.4.*
  - pillow=6.2.1
  - pyyaml=5.3
  - marshmallow=3.4.0
  - pytest=4.3.0
  - grpcio=1.31
  - grpcio-tools
  - protobuf=3.11.4
  - cudatoolkit>=10.1,<10.2
  - numpy=1.18.5
  - cudnn
  - black
  - isort
  - conda-build
  - anaconda-client
  - bump2version
  - pre_commit
  - scikit-learn
  - pip:
      - tensorflow
      - pytest-grpc==0.7.0
      - git+https://github.com/bioimage-io/python-bioimage-io#egg=pybio # bump again
